import {
  compareSubjects,
  createEvidenceArtifact,
  createCandidateSet,
  createExport,
  createScenarioArtifact,
  createSimulationRun,
  getEvidenceArtifact,
  getCandidateSet,
  getObservationEvidence,
  getScenarioArtifact,
  getSimulationRun,
  getSubjectSnapshot,
  patchCandidateSet,
  queryAtlasLayers,
  queryForecast,
  queryRhythm,
} from './handlers.js';

export {
  compareSubjects,
  createEvidenceArtifact,
  createCandidateSet,
  createExport,
  createScenarioArtifact,
  createSimulationRun,
  getEvidenceArtifact,
  getCandidateSet,
  getObservationEvidence,
  getScenarioArtifact,
  getSimulationRun,
  getSubjectSnapshot,
  patchCandidateSet,
  queryAtlasLayers,
  queryForecast,
  queryRhythm,
};

export const apiV1Handlers = {
  compareSubjects,
  createEvidenceArtifact,
  createCandidateSet,
  createExport,
  createScenarioArtifact,
  createSimulationRun,
  getEvidenceArtifact,
  getCandidateSet,
  getObservationEvidence,
  getScenarioArtifact,
  getSimulationRun,
  getSubjectSnapshot,
  patchCandidateSet,
  queryAtlasLayers,
  queryForecast,
  queryRhythm,
};
